### ISSUE TITLE
`from odmd import OnlineDMD` 

### ISSUE THREAD

**Issue by wulidede** [wenjianhao/Deep-Koopman-learning-of-nonlinear-time-varying-systems#1]
On line 33 of main.py, the import statement `from odmd import OnlineDMD` seems to reference a Python file named "odmd" that does not appear to exist in the library. Could it be that you have overlooked this file?

**Comment by wulidede** [comment]
On line 21 of plot_compare.py, the import statement `from LNNsl import LNNsl` appears to have the same issue？

**Comment by wulidede** [comment]
Sorry, I have known the `odmd` is a python package for online dynamic mode decomposition and I have successfully installed it. But where is `LNNsl`?

**Comment by wenjianhao** [comment]
thank you for your comments. 
(1) Yes odmd is a third party package which can be installed by pip, and (2) I updated the LNN.py file to include the DNN structure of the MLP method for comparison. 
Download the new LNN.py file -> run the main.py file -> run the plot file, you shall be fine.

**Comment by wulidede** [comment]
Thank you for your response! Additionally, there is a minor error in plot_compare.py. On line 21 of this file, `from LNNsl import LNNsl` should be `from LNN import LNNsl`.

**Comment by wenjianhao** [comment]
cool, i corrected that. Thx for the reminder.
